version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: meridian-backend
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      sh -lc "
        pip install --no-cache-dir -r requirements.txt &&
        python -m flask --app app:app run --host 0.0.0.0 --port 8000 --debug
      "
    networks: [appnet]

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: meridian-front
    environment:
      VITE_API_BASE_URL: "http://localhost:8000"
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: >
      sh -lc "
        if [ -f package-lock.json ]; then npm ci; else npm i; fi &&
        npm run dev -- --host 0.0.0.0 --port 5173
      "
    depends_on: [backend]
    networks: [appnet]

networks:
  appnet:
    driver: bridge
